#!/usr/bin/env bash
# awa-down 이 .boot-settings/ 제거 확인.
# T19: state 디렉터리 정리(게이트 안) 검증. 6차: 데몬 폐기 — watch-asks/tail-pids 단언 제거.
set -uo pipefail
cd "$(dirname "$0")"
source ./assert.sh
source ./harness-paths.sh

ROOT="$(cd .. && pwd)"
TMP="$(mktemp -d)"
SAFE="$(printf '%s' "$(basename "$TMP")" | sed 's/[^A-Za-z0-9_-]/_/g')"
SESSION="awa-$SAFE"

# 15th: bookmarks 격리 — awa-up.sh 가 ~/.config/awa/bookmarks.tsv 에 기록.
# 테스트 fixture 가 사용자 실 경로를 더럽히지 않도록 임시 dir 로 redirect.
_AGPN15_XDG="$(mktemp -d)"
export XDG_CONFIG_HOME="$_AGPN15_XDG"

cleanup() {
  tmux kill-session -t "$SESSION" 2>/dev/null || true
  rm -rf "$TMP"
  [ -n "${_AGPN15_XDG:-}" ] && rm -rf "$_AGPN15_XDG"
}
trap cleanup EXIT
( cd "$TMP" && git init -q )

HARNESS_PROJECT="$TMP" AGENT_CMD=cat bash "$HARNESS_BIN/awa-up.sh" feature-team >/dev/null 2>&1

# awa-up 후 권한 산출물 + 사용자 흔적 만들기.
WS="$TMP/.agent-harness"
mkdir -p "$WS/.boot-settings"
echo '{"x":"y"}' > "$WS/.boot-settings/dev.json"

# T19: marker 생성 (게이트 안 정리가 실행되려면 marker 필요).
mkdir -p "$TMP/.claude"
printf 'generated by agent-harness\n' > "$TMP/.claude/.agent-harness-marker"

# T19: state 디렉터리 fixture (게이트 안 정리 대상).
mkdir -p "$WS/state/pending-asks" "$WS/state/incidents" "$WS/state/removal-requests"
echo '{}' > "$WS/state/pending-asks/u1.json"
echo '{}' > "$WS/state/incidents/i1.json"
echo "ts dev - PRE Bash" > "$WS/state/permission-gate.log"   # 6차 게이트 로그 정리 검증

# awa-down 실행
HARNESS_PROJECT="$TMP" bash "$HARNESS_BIN/awa-down.sh" >/dev/null 2>&1

[ ! -d "$WS/.boot-settings" ]; assert_success "$?" ".boot-settings 제거"

# 기존 cleanup 동작 회귀
[ ! -d "$WS/.boot" ] || [ -z "$(ls "$WS/.boot"/*.md 2>/dev/null)" ]
assert_success "$?" ".boot/*.md 제거 (기존 동작)"

# T19/6차: state 디렉터리 + 게이트 로그 정리 단언 (데몬 폐기 — 데몬 파일 단언 제거).
echo "[D-state] awa-down 후 pending-asks/incidents/removal 정리"
[ ! -d "$WS/state/pending-asks" ]; assert_success "$?" "pending-asks 정리"
[ ! -d "$WS/state/incidents" ]; assert_success "$?" "incidents 정리"
[ ! -d "$WS/state/removal-requests" ]; assert_success "$?" "state/removal-requests 제거"
[ ! -f "$WS/state/permission-gate.log" ]; assert_success "$?" "permission-gate.log 제거 (6차 게이트)"

test_summary
