#!/usr/bin/env bash
# team-down 이 .boot-settings/·permission-events.log·.lead-perm-cursor 제거 확인.
# T19: watch-asks 데몬 종료(게이트 밖) + state 디렉터리 정리(게이트 안) 검증 추가.
set -uo pipefail
cd "$(dirname "$0")"
source ./assert.sh

ROOT="$(cd .. && pwd)"
TMP="$(mktemp -d)"
SAFE="$(printf '%s' "$(basename "$TMP")" | sed 's/[^A-Za-z0-9_-]/_/g')"
SESSION="agents-$SAFE"

cleanup() {
  tmux kill-session -t "$SESSION" 2>/dev/null || true
  rm -rf "$TMP"
}
trap cleanup EXIT
( cd "$TMP" && git init -q )

HARNESS_PROJECT="$TMP" AGENT_CMD=cat bash "$ROOT/bin/team-up.sh" feature-team >/dev/null 2>&1

# team-up 후 권한 산출물 + 사용자 흔적 만들기.
WS="$TMP/.agent-harness"
mkdir -p "$WS/.boot-settings"
echo '{"x":"y"}' > "$WS/.boot-settings/dev.json"
echo 'ts dev - PRE Bash rm' > "$WS/permission-events.log"
echo "0" > "$WS/.lead-perm-cursor"

# T19: marker 생성 (게이트 안 정리가 실행되려면 marker 필요).
mkdir -p "$TMP/.claude"
printf 'generated by agent-harness\n' > "$TMP/.claude/.agent-harness-marker"

# T19: state 디렉터리 fixture (게이트 안 정리 대상).
mkdir -p "$WS/state/pending-asks" "$WS/state/incidents" "$WS/state/removal-requests"
echo '{}' > "$WS/state/pending-asks/u1.json"
echo '{}' > "$WS/state/incidents/i1.json"
printf 'arch %%5 sid /tmp/a.jsonl researcher\n' > "$WS/state/workers.list"
echo "log" > "$WS/state/watch-asks.log"
echo "99999" > "$WS/state/watch-asks.pid"   # 존재하지 않는 PID (kill 무해)
echo "99998" > "$WS/state/tail-pids"   # SIGKILL 경로의 tail-pids 잔존 정리 검증

# team-down 실행
HARNESS_PROJECT="$TMP" bash "$ROOT/bin/team-down.sh" >/dev/null 2>&1

[ ! -d "$WS/.boot-settings" ]; assert_success "$?" ".boot-settings 제거"
[ ! -f "$WS/permission-events.log" ]; assert_success "$?" "permission-events.log 제거"
[ ! -f "$WS/.lead-perm-cursor" ]; assert_success "$?" ".lead-perm-cursor 제거"

# 기존 cleanup 동작 회귀
[ ! -d "$WS/.boot" ] || [ -z "$(ls "$WS/.boot"/*.md 2>/dev/null)" ]
assert_success "$?" ".boot/*.md 제거 (기존 동작)"

# T19: state 디렉터리 + 데몬 파일 정리 단언.
[ ! -d "$WS/state/pending-asks" ]; assert_success "$?" "state/pending-asks 제거"
[ ! -d "$WS/state/incidents" ]; assert_success "$?" "state/incidents 제거"
[ ! -d "$WS/state/removal-requests" ]; assert_success "$?" "state/removal-requests 제거"
[ ! -f "$WS/state/workers.list" ]; assert_success "$?" "workers.list 제거"
[ ! -f "$WS/state/watch-asks.log" ]; assert_success "$?" "watch-asks.log 제거"
[ ! -f "$WS/state/watch-asks.pid" ]; assert_success "$?" "watch-asks.pid 제거 (데몬 종료)"
[ ! -f "$WS/state/tail-pids" ]; assert_success "$?" "tail-pids 제거 (SIGKILL 경로)"

test_summary
